config/routes.rb
Rails.application.routes.draw do
  resources :posts, path: "blog" do
    resources :comments, only: [:create]
  end
  root 'welcome#home'

  get '/about' => 'welcome#about'
  get '/contact' => 'welcome#contact'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	# Validations 
	validates :body, length: { minimum: 5 }, presence: true

	# Relationships
  belongs_to :post
  
end

app/models/post.rb
class Post < ActiveRecord::Base
	# Validations
	validates :title, presence: true
	validates :body, presence: true
	validates :slug, uniqueness: true, presence: true

	before_validation :generate_slug

	# Relationships
	has_many :comments

	def to_param
		slug
	end

	def generate_slug
		self.slug ||= title.parameterize
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		@post = Post.find_by_slug!(params[:post_id])
		@comment = @post.comments.build(params.require(:comment).permit(:body))
		if @comment.save
			redirect_to @post, notice: "Thank you for your comment!"
		else
			redirect_to @post, notice: "There was an error saving your comment. Please try again."
		end
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.paginate(page: params[:page], per_page: 10)
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @comment = @post.comments.build
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find_by_slug!(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def markdown(text)
		renderer = Redcarpet::Render::HTML.new
		extensions = {fenced_code_blocks: true}
		redcarpet = Redcarpet::Markdown.new(renderer, extensions)
		(redcarpet.render text).html_safe
	end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_form.html.erb
<%= form_for [post, comment] do |f| %>
	<% if comment.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>
        <ul>
        <% comment.errors.fu ll_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <!-- Add a Comment Form --> 
    <div class="form-group">
    	<%= f.text_area :body, class: "form-control" %>
    </div>
    <div class="actions">
    	<%= f.submit "Save Comment", class: "btn btn-primary" %>
    </div>
<% end %>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to "Your Name Here", root_path, class: "navbar-brand" %>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li> 
      <li><%= link_to "Blog", posts_path %></li>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

	<head>
	  <title>Blog</title>
	  <meta name="viewport" content="width=device-width, initial-scale=1">
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>
	</head>
	
	<body>
	
		<%= render 'layouts/nav' %>

		<div class="container-fluid">

			<%= yield %>
			
		</div>

	</body>
</html>

app/views/posts/_form.html.erb
<div class="panel-body">
  <%= form_for(@post) do |f| %>
    <% if @post.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

        <ul>
        <% @post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= f.label :title %><br>
      <%= f.text_field :title, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :body %><br>
      <%= f.text_area :body, class: "form-control" %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
</div>
  

app/views/posts/edit.html.erb
<div class="row">
	<div class="panel col-md-8 col-md-offset-2">
		<h1>Edit My Post</h1>
		<%= render 'form' %>

		<%= link_to 'Show', @post %> |
		<%= link_to 'Back', posts_path %>
	</div>
</div>


		

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<div id="blog-index">
  <% @posts.each do |post| %>
    <div class="row">
      <div class="col-md-8 col-md-offset-2 individual-post">
        <h2><%= link_to post.title, post, class: "text" %></h2>
        <p><%= link_to post.body, post, class: "text" %><%= link_to "  read more >", post %></p>
        
      </div>
    </div>
  <% end %>

  <div class="row">
    <div class="col-md-12 text-center">
      <%= will_paginate @posts %>
    </div>
  </div>
</div>
  




<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<div class="row">
  <div class="panel col-md-8 col-md-offset-2">
    <h1>New Post</h1>
    <%= render 'form' %>
    <%= link_to 'Back', posts_path %>
  </div>
</div>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<div id="blog-show">
	<div class="row">
		<div class="col-md-8 col-md-offset-2 individual-post">
			<h1><%= markdown @post.title %></h1>
			<p><%= markdown @post.body %></p>
			<p><%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %></p>
		</div>
	</div>

	<!-- Comments -->
	<div class="row">
		<div class="col-md-8 col-md-offset-2 individual-post">
			<div class="comment">
			<% if @post.comments.count === 0 %>
				<h5>No comments. Add one now.</h5>
			<% else %>
				<h4><%= pluralize(@post.comments.count, 'Comment') %>:</h4>
				<% @post.comments.each do |comment| %>
					<p><%= comment.body %></p>
				<% end %>
			<% end %>
			</div>
			<%= render partial: 'comments/form', locals: { post: @post, comment: @comment } %>
		</div>
	</div>
</div>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/contact.html.erb
<h1>Contact Me</h1>

app/views/welcome/home.html.erb
<div class="jumbotron">
	<h1>Welcome to my home page!</h1>
	<p>You can learn more <%= link_to "about me", about_path %> or <%= link_to "contact me", contact_path %>  at any time. </p>
</div>
	